base = "region_name"

[[rulesets]]
[rulesets.rules]
"{name}" = "{name}"

[[rulesets]]
name = "name"
[rulesets.rules]
"The {1} {2}" = "{1} {2}"
"The {1} of {2}" = "{2}의 {1}"
"The {1} {2} of {3}" = "{3}의 {1} {2}"
"The {1} of {2} {3}" = "{2} {3}의 {1}"
"The {1} {2} {3}" = "{1} {2} {3}"


[[rulesets]]
name = "1"
[rulesets.rules]
"{::adjword::adjall}" = "{::adjword::adjall}"  
"{1}-{2}" = "{1}-{2}"

[[rulesets]]
name = "2"
[rulesets.rules]
"{::adjword::adjall}" = "{::adjword::adjall}"    
"{1}-{2}" = "{1}-{2}"

[[rulesets]]
name = "3"
[rulesets.rules]
"{::adjword::adjall}" = "{::adjword::adjall}"  
"{1}-{2}" = "{1}-{2}"