base = "require"

[[rulesets]]
[rulesets.rules]
"[Requires {main}]" = "[{main} 필요]"

[[rulesets]]
name = "main"
[rulesets.rules]
"Unrotten fermentable leaf or fruit" = "썩지 않은 발효 가능한 잎 또는 과일"
"Unrotten fermentable plants" = "썩지 않은 발효 가능한 식물"
"Honey-containing item" = "꿀이 든 물품"
"Potash" = "칼륨"
"Clay boulders" = "점토"
"Empty bag" = "빈 가방"
"Empty unimproved glazable item" = "유약칠 가능한 빈 물품"
"Empty unimproved glazable jug" = "유약칠 가능한 빈 주전자"
"Empty unimproved glazable statue" = "유약칠 가능한 빈 조각상"
"Empty unimproved glazable large pot" = "유약칠 가능한 빈 큰 단지"
"Gypsum boulders" = "석고 돌덩이"
"Calcite/limestone/chalk/marble boulders" = "방해석/석회암/백악/대리석 돌덩이"
"Window" = "창문"
"Plant logs" = "식물 통나무"
"Oil-containing item" = "기름이 든 물품"
"Unrotten tallow fatty glob" = "썩지 않은 동물지방 덩어리"
"Lye-containing item" = "양잿물이 든 물품"
"Scroll rollers" = "두루마리 축"
"Wax glob" = "밀랍 덩어리"
"Collected thread" = "수집된 실"
"Sheet" = "종이"
"Book binding" = "책 제본"
"Unrotten bone body part" = "썩지 않은 뼈"
"Logs" = "통나무"
"Non-economic hard stone boulders" = "비경제적 단단한 돌"
"Unrotten shell body part" = "썩지 않은 껍데기"
"Collected plant thread" = "수집된 식물성 실"
"Unrotten paper-making plants" = "썩지 않은 제지용 식물"
"Milk of lime-containing item" = "석회유가 든 물품"
"Unrotten tannable body part" = "썩지 않은 무두질 가능한 가죽"
"Empty bucket" = "빈 양동이"
"Quicklime-containing item" = "생석회가 든 물품"
"Non-pressed honey-bearing honeycomb" = "압착하지 않은 꿀이 든 벌집"
"Unrotten non-pressed oil-bearing leaf or fruit" = "썩지 않은 압착전 기름 함유 잎 또는 과일"
"Non-pressed oil-bearing glob" = "압착전 기름 함유 덩어리"
"Non-pressed paper-slurry glob" = "압착전 펄프 덩어리"
"Liquid container" = "액체 용기"
"Tanned hide" = "무두질한 가죽"
"Unrotten paper-slurryable plants" = "썩지 않은 펄프용 식물"
"Unrotten oil-bearing seeds" = "썩지 않은 기름 함유 씨앗"
"Sand-containing item" = "모래가 든 물품"
"Written-on quire" = "글이 쓰인 종이 묶음"
"Flux boulders" = "용해제 돌덩이"
"fuel" = "연료"
"ore" = "광석"
"ore, fuel" = "광석, 연료"
"Bituminous coal" = "역청탄"
"Lignite" = "갈탄"
"Adamantine strands" = "아다만틴 실"
"Zinc-bearing boulders" = "아연 함유 돌덩이"
"Tin-bearing boulders" = "주석 함유 돌덩이"
"Copper-bearing boulders" = "구리 함유 돌덩이"
"Silver-bearing boulders" = "은 함유 돌덩이"
"Gold-bearing boulders" = "금 함유 돌덩이"
"{::materials} ore" = "{::materials} 광석"
"{::items::bar}" = "{::items::bar}"
"Refined coal" = "정제된 석탄"