base = "menu::weave"

[[rulesets]]
[rulesets.rules]
# 어순 변경: [재료]로 [결과물] [짜기]
# 예: 실로 천 짜기
"{kind}{main}{goods}" = "{main} {goods} {kind}"

# 특수 재질(금속/아다만틴 등)의 경우
# 예: 금속 천 짜기
"{kind}{main::special}{goods}" = "{main::special} {goods} {kind}"

[[rulesets]]
name = "kind"
[rulesets.rules]
"Weave" = "짜기"

[[rulesets]]
name = "main"
[rulesets.rules]
# 원문의 ' thread into'를 한국어 조사 '로'를 포함하여 번역
" thread into" = "실로"
" yarn into" = "털실로"

[[rulesets]]
name = "main::special"
[rulesets.rules]
" metal" = "금속"

[[rulesets]]
name = "goods"
[rulesets.rules]
" cloth" = "천"
" silk" = "비단"