base = "dwarf_language::adj"

[[rulesets]]
name = "main"
[rulesets.rules]
"Med" = "메드"
"Ilas" = "일라스"
"Sosas" = "소사스"
"Ngalák" = "날라크"
"Kuthdêng" = "쿠스뎅"
"Alak" = "알라크"
"Agseth" = "아그세스"
"Tatek" = "타테크"
"Nebél" = "네벨"
"Salir" = "살리르"
"Cenäth" = "세나스"
"Thokit" = "소키트"
"Gatal" = "가탈"
"Anzish" = "안지쉬"
"Astel" = "아스텔"
"Edos" = "에도스"
"Thukkan" = "수칸"
"Umgan" = "움간"
"Alron" = "알론"
"Ïdath" = "이다스"
"Zustash" = "주스타쉬"
"Sedil" = "세딜"
"Ustos" = "우스토스"
"Roldeth" = "롤데스"
"Ungòb" = "운곱"
"Útost" = "우토스트"
"Kíddir" = "키디르"
"Tosid" = "토시드"
"Berim" = "베림"
"Ibruk" = "이브루크"
"Mangròd" = "망그로드"
"Arist" = "아리스트"
"Sanus" = "사누스"
"Shigin" = "쉬긴"
"Thatthil" = "사틸"
"Gòstang" = "고스탕"
"Kithäl" = "키셀"
"Asdos" = "아스도스"
"Neth" = "네스"
"Roder" = "로더"
"Emäth" = "에메스"
"Bashnom" = "바쉬놈"
"Tholtig" = "솔티그"
"Enseb" = "엔세브"
"Durad" = "두라드"
"Kinem" = "키넴"
"Theb" = "세브"
"Arom" = "아롬"
"Îmäz" = "이메즈"
"Mat" = "마트"
"Zutshosh" = "주트쇼쉬"
"Nonshut" = "논슈트"
"Etäg" = "에타그"
"Nóton" = "노톤"
"Räduk" = "라두크"
"Udir" = "우디르"
"Ustan" = "우스탄"
"Lål" = "랄"
"Sharsid" = "샤르시드"
"Nural" = "누랄"
"Okag" = "오카그"
"Medtob" = "메드토브"
"Nashon" = "나숀"
"Kod" = "코드"
"Etes" = "에테스"
"Enôr" = "에노르"
"Unâl" = "우날"
"Murak" = "무라크"
"Edod" = "에도드"
"Ärged" = "아르게드"
"Nakuth" = "나쿠스"
"Zes" = "제스"
"Midrim" = "미드림"
"Konos" = "코노스"
"Âtast" = "아타스트"
"Urthaz" = "우르사즈"
"Shalig" = "샬리그"
"Shin" = "신"
"Äkim" = "아킴"
"Kilrud" = "킬루드"
"Neb" = "네브"
"Nosing" = "노싱"
"Tîrdug" = "티르두그"
"Itred" = "이트레드"
"Gubel" = "구벨"
"Kitïg" = "키티그"
"Reked" = "레케드"
"Rorash" = "로라쉬"
"Betan" = "베탄"
"Luthoz" = "루소즈"
"Thastith" = "사스티스"
"Sheced" = "셰세드"
"Kor" = "코르"
"Fazís" = "파지스"
"Ós" = "오스"
"Remang" = "레망"
"Athser" = "아세르"
"Ngusham" = "구샴"
"Musöd" = "무소드"
"Debben" = "데벤"
"Gingik" = "긴기크"
"Rangab" = "랑가브"
"Bor" = "보르"
"Kontuth" = "콘투스"
"Oshur" = "오슈르"
"Assar" = "아사르"
"Lecad" = "레카드"
"Es" = "에스"
"Lir" = "리르"
"Urol" = "우롤"
"Lun" = "룬"
"Teling" = "텔링"
"Letmos" = "레트모스"
"Rafum" = "라품"
"Nekik" = "네키크"
"Mekur" = "메쿠르"
"Artob" = "아르토브"
"Resíl" = "레실"
"Ultèr" = "울테르"
"Âgoth" = "아고스"
"Ádol" = "아돌"
"Thikén" = "티켄"
"Kacoth" = "카코스"
"Shadmal" = "샤드말"
"Kezkíg" = "케즈키그"
"Nucam" = "누캄"
"Aban" = "아반"
"Etost" = "에토스트"
"Gishgil" = "기쉬길"
"Ágesh" = "아게쉬"
"Mingtuth" = "밍투스"
"Letom" = "레톰"
"Etnàr" = "에트나르"
"Gusil" = "구실"
"Shusug" = "슈수그"
"Samam" = "사맘"
"Tustem" = "투스템"
"Obot" = "오보트"
"Arban" = "아르반"
"Sulus" = "술루스"
"Uling" = "울링"
"Dîbesh" = "디베쉬"
"Berath" = "베라스"
"Dôbar" = "도바르"
"Innok" = "이노크"
"Orshet" = "오르셰트"
"Zim" = "짐"
"Ginet" = "기네트"
"Thestar" = "세스타르"
"Gesul" = "게술"
"Thad" = "사드"
"Luror" = "루로르"
"Zas" = "자스"
"Nakis" = "나키스"
"Kesham" = "케샴"
"Amem" = "아멤"
"Nguteg" = "구테그"
"Gikut" = "기쿠트"
"Kezat" = "케자트"
"Unul" = "우눌"
"Umom" = "우몸"
"Nökor" = "노코르"
"Asen" = "아센"
"Ethad" = "에사드"
"Sestan" = "세스탄"
"Inir" = "이니르"
"Thol" = "솔"
"Alûth" = "알루스"
"Nadak" = "나다크"
"Nirmek" = "니르메크"
"Ûlmush" = "울무쉬"
"Arbost" = "아르보스트"
"Amith" = "아미스"
"Geb" = "게브"
"Ozon" = "오존"
"Nam" = "남"
"Sîbosh" = "시보쉬"
"Manthul" = "만술"
"Sholkik" = "숄키크"
"Doren" = "도렌"
"Zengod" = "젠고드"
"Arösh" = "아로쉬"
"Lunrud" = "룬루드"
"Storlut" = "스토르루트"
"Bekar" = "베카르"
"Gorroth" = "고로스"
"Shungmag" = "슝마그"
"Vetor" = "베토르"
"Assog" = "아소그"
"Nobang" = "노방"
"Olum" = "올룸"
"Ruthösh" = "루소쉬"
"Tastrod" = "타스트로드"
"Ashzos" = "아슈조스"
"Nabas" = "나바스"
"Rodnul" = "로드눌"
"Akest" = "아케스트"
"Okbod" = "오크보드"
"Gomóm" = "고몸"
"Rem" = "렘"
"Bibar" = "비바르"
"Zêvut" = "제부트"
"Nåzom" = "나좀"
"Thikthog" = "식소그"
"Shuk" = "슈크"
"Rumad" = "루마드"
"Etest" = "에테스트"
"Ôler" = "올레르"
"Ed" = "에드"
"Ber" = "베르"
"Em" = "엠"
"Utal" = "우탈"
"Rùkal" = "루칼"
"Okir" = "오키르"
"Todör" = "토도르"
"Kastol" = "카스톨"
"Kurol" = "쿠롤"
"Sedur" = "세두르"
"Kisat" = "키사트"
"Minbaz" = "민바즈"
"Nakas" = "나카스"
"Stistmig" = "스티스트미그"
"Desor" = "데소르"
"Sharast" = "샤라스트"
"Tinöth" = "티노스"
"Maskir" = "마스키르"
"Othör" = "오소르"
"Ninur" = "니누르"
"Ostath" = "오스타스"
"Zilir" = "질리르"
"Râmol" = "라몰"
"Esäst" = "에사스트"
"Dèg" = "데그"
"Ïssun" = "이순"
"Ilus" = "일루스"
"Gedor" = "게도르"
"Egståk" = "에그스타크"
"Thasdoth" = "사스도스"
"Zamnuth" = "잠누스"
"Sankest" = "산케스트"
"Uzlir" = "우즐리르"
"Öndin" = "온딘"
"Ungèg" = "운게그"
"Losis" = "로시스"
"Angen" = "안겐"
"Anûz" = "아누즈"
"Tabar" = "타바르"
"Seth" = "세스"
"Belal" = "벨랄"
"Shan" = "샨"
"Lemlor" = "렘로르"
"Er" = "에르"
"Odroz" = "오드로즈"
"Tarem" = "타렘"
"Ked" = "케드"
"Igrish" = "이그리쉬"
"Ustuth" = "우스투스"
"Ekzong" = "엑종"
"Nidòst" = "니도스트"
"Korsid" = "코르시드"
"Lithrush" = "리스루쉬"
"Dotir" = "도티르"
"Zikel" = "지켈"
"Ziril" = "지릴"
"Uthar" = "우사르"
"Engig" = "엔기그"
"Gonggash" = "공가쉬"
"Astan" = "아스탄"
"Ar" = "아르"
"Nëlas" = "넬라스"
"Rersîr" = "레르실"
"Tetist" = "테티스트"
"Totmon" = "토트몬"
"Amug" = "아무그"
"Ost" = "오스트"
"Gatiz" = "가티즈"
"Cabnul" = "카브눌"
"Gïsstir" = "기스티르"
"Akam" = "아캄"
"Inglaz" = "잉글라즈"
"Shosêl" = "쇼셀"
"Eshim" = "에쉼"
"Emet" = "에메트"
"Babin" = "바빈"
"Shasar" = "샤사르"
"Ishol" = "이숄"
"Thîdas" = "시다스"
"Nisgak" = "니스가크"
"Gulgun" = "굴군"
"Dozeb" = "도제브"
"Sunggor" = "숭고르"
"Esmul" = "에스물"
"Thusest" = "수세스트"
"Zalud" = "잘루드"
"Shistat" = "쉬스타트"
"Zisur" = "지수르"
"Olon" = "올론"
"Oltar" = "올타르"
"Gintar" = "긴타르"
"Saruth" = "사루스"
"Usir" = "우시르"
"Amkin" = "암킨"
"Àlil" = "알릴"
"Eser" = "에세르"
"Vumshar" = "붐샤르"
"Anil" = "아닐"
"Reg" = "레그"
"Rab" = "라브"
"Ngobol" = "고볼"
"Löbor" = "로보르"
"Nòm" = "놈"
"Bunsoth" = "분소스"
"Limul" = "리물"
"Thistun" = "시스툰"
"Eshon" = "에숀"
"Dedros" = "데드로스"
"Zugob" = "주고브"
"Lolok" = "롤로크"
"Gídthur" = "기드수르"
"Bel" = "벨"
"Saràm" = "사람"
"Riras" = "리라스"
"Töras" = "토라스"
"Omer" = "오메르"
"Nothis" = "노시스"
"Usith" = "우시스"
"Mithmis" = "미스미스"
"Enol" = "에놀"
"Edtûl" = "에드툴"
"Thólthod" = "솔소드"
"Lushût" = "루슈트"
"Óruk" = "오루크"
"Bistök" = "비스토크"
"Vosut" = "보수트"
"Oddet" = "오데트"
"Ifin" = "이핀"
"Thir" = "시르"
"Gethust" = "게수스트"
"Lur" = "루르"
"Mis" = "미스"
"Ikal" = "이칼"
"Vúsh" = "부쉬"
"Dasël" = "다셀"
"Danman" = "단만"
"Köshdes" = "코쉬데스"
"Shash" = "샤쉬"
"Zon" = "존"
"Usen" = "우센"
"Oshosh" = "오쇼쉬"
"Obur" = "오부르"
"Lirlez" = "리르레즈"
"Erlin" = "에를린"
"Goster" = "고스터"
"Kegeth" = "케게스"
"Ugosh" = "우고쉬"
"Kiron" = "키론"
"Nakbab" = "나크바브"
"Gadan" = "가단"
"Dural" = "두랄"
"Zanos" = "자노스"
"Vir" = "비르"
"Kàlreth" = "칼레스"
"Alek" = "알렉"
"Fokásh" = "포카쉬"
"Ushil" = "우실"
"Gumùr" = "구무르"
"Anist" = "아니스트"
"Mimkot" = "밈코트"
"Nizdast" = "니즈다스트"
"Enen" = "에넨"
"Osstam" = "오스타므"
"Kudar" = "쿠다르"
"Thalal" = "살랄"
"Kadän" = "카덴"
"Ushesh" = "우셰쉬"
"Goshîst" = "고쉬스트"
"Dalem" = "달렘"
"Òrdir" = "오르디르"
"Mengthul" = "멩술"
"Thêmnol" = "셈놀"
"Mishim" = "미쉼"
"Tellist" = "텔리스트"
"Sedish" = "세디쉬"
"Avûsh" = "아부쉬"
"Gemis" = "게미스"
"Êr" = "에르"
"Immast" = "이마스트"
"Likot" = "리코트"
"Etóm" = "에톰"
"Ethzuth" = "에스주스"
"Lûk" = "루크"
"Rinul" = "리눌"
"Izkil" = "이즈킬"
"Nelzur" = "넬주르"
"Sosad" = "소사드"
"Otil" = "오틸"
"Bukshon" = "북숀"
"Istrath" = "이스트라스"
"Ilir" = "일리르"
"Imketh" = "임케스"
"Stizash" = "스티자쉬"
"Nosîm" = "노심"
"Musar" = "무사르"
"Èrith" = "에리스"
"Lumnum" = "룸눔"
"Vakist" = "바키스트"
"Elol" = "엘롤"
"Ralâth" = "랄라스"
"Merrang" = "메랑"
"Bul" = "불"
"Or" = "오르"
"Onam" = "오남"
"Ulol" = "울롤"
"Et" = "에트"
"Gébar" = "게바르"
"Ngefel" = "게펠"
"Omoth" = "오모스"
"Govos" = "고보스"
"Orab" = "오라브"
"Dalkam" = "달캄"
"Turel" = "투렐"
"Gudos" = "구도스"
"Gomath" = "고마스"
"Gudid" = "구디드"
"Gekur" = "게쿠르"
"Thunen" = "수넨"
"Istam" = "이스탐"
"Dithbish" = "디스비쉬"
"Vel" = "벨"
"Tokmek" = "토크메크"
"Azzin" = "아진"
"Tetóth" = "테토스"
"Nimem" = "니멤"
"Numol" = "누몰"
"Romek" = "로메크"
"Uleng" = "울렝"
"Aval" = "아발"
"Lushòb" = "루쇼브"
"Damèl" = "다멜"
"Ekir" = "에키르"
"Merseth" = "메르세스"
"Vurtib" = "부르티브"
"Lelgas" = "렐가스"
"Nethgön" = "네스곤"
"Suvas" = "수바스"
"Ertal" = "에르탈"
"Avan" = "아반"
"Aroth" = "아로스"
"Sezom" = "세좀"
"Ezost" = "에조스트"
"Tustzal" = "투스트잘"
"Tongus" = "통구스"
"Kùgneb" = "쿠그네브"
"Sutung" = "수퉁"
"Imust" = "이무스트"
"Shashdon" = "샤쉬돈"
"Zansong" = "잔송"
"Dalzat" = "달자트"
"Tad" = "타드"
"Mëbnith" = "메브니스"
"Ûbom" = "우봄"
"Fashuk" = "파슈크"
"Ablish" = "아블리쉬"
"Bëmbul" = "벰불"
"Unob" = "우노브"
"Kir" = "키르"
"Milol" = "밀롤"
"Ekur" = "에쿠르"
"Ottan" = "오탄"
"Gitnuk" = "기트누크"
"Sebshos" = "세브쇼스"
"Lêgan" = "레간"
"Cemosh" = "세모쉬"
"Sôd" = "소드"
"Èrnam" = "에르남"
"Idash" = "이다쉬"
"Stesok" = "스테소크"
"Zavaz" = "자바즈"
"Ushang" = "우샹"
"Tumam" = "투맘"
"Ednàd" = "에드나드"
"Tunom" = "투놈"
"Osresh" = "오스레쉬"
"Tel" = "텔"
"Onol" = "오놀"
"Leshal" = "레샬"
"Stoling" = "스톨링"
"Godum" = "고둠"
"Shislug" = "쉬슬루그"
"Ol" = "올"
"Bothon" = "보손"
"Thum" = "숨"
"Shasad" = "샤사드"
"Arrug" = "아루그"
"Rul" = "룰"
"Shoveth" = "쇼베스"
"Lathon" = "라손"
"Kab" = "카브"
"Dast" = "다스트"
"Thubil" = "수빌"
"Solam" = "솔람"
"Egom" = "에곰"
"Kêdnath" = "케드나스"
"Ngutug" = "구투그"
"Ital" = "이탈"
"Ir" = "이르"
"Rîthol" = "리솔"
"Zaled" = "잘레드"
"Irol" = "이롤"
"Lisat" = "리사트"
"Katthir" = "카티르"
"Rodïm" = "로딤"
"Kin" = "킨"
"Nothok" = "노소크"
"Thokdeg" = "소크데그"
"Azmol" = "아즈몰"
"Äsrath" = "아스라스"
"Migrur" = "미그루르"
"Nokim" = "노킴"
"Kebon" = "케본"
"Uzol" = "우졸"
"Egar" = "에가르"
"Losush" = "로수쉬"
"Zocuk" = "조쿠크"
"Som" = "솜"
"Shed" = "셰드"
"Stegëth" = "스테게스"
"Zar" = "자르"
"Dáthnes" = "다스네스"
"Zulash" = "줄라쉬"
"Abal" = "아발"
"Fash" = "파쉬"
"Ishen" = "이셴"
"Geth" = "게스"
"Lîlar" = "릴라르"
"Bisól" = "비솔"
"Ator" = "아토르"
"Ìrlom" = "일롬"
"Sherik" = "셰리크"
"Eges" = "에게스"
"Othbem" = "오스벰"
"Bimmon" = "비몬"
"Mamot" = "마모트"
"Kugik" = "쿠기크"
"Titthal" = "티탈"
"Udist" = "우디스트"
"Dimshas" = "딤샤스"
"Äkil" = "아킬"
"Inrus" = "인루스"
"Deleth" = "델레스"
"Umshad" = "움샤드"
"Niral" = "니랄"
"Libad" = "리바드"
"Merir" = "메리르"
"Udiz" = "우디즈"
"Gemur" = "게무르"
"Enal" = "에날"
"Zèler" = "젤레르"
"Stibbom" = "스티봄"
"Maram" = "마람"
"Batôk" = "바토크"
"Vildang" = "빌당"
"Bidnoz" = "비드노즈"
"Furgig" = "푸르기그"
"Fongbez" = "퐁베즈"
"Enam" = "에남"
"Thetust" = "세투스트"
"Rushrul" = "루슈룰"
"Uvir" = "우비르"
"Luslem" = "루슬렘"
"Bukèt" = "부케트"
"Esar" = "에사르"
"Kàs" = "카스"
"Atêsh" = "아테쉬"
"Udar" = "우다르"
"Zokgen" = "조크겐"
"Serkib" = "세르키브"
"Ong" = "옹"
"Asàs" = "아사스"
"Akrel" = "아크렐"
"När" = "나르"
"Orstist" = "오르스티스트"
"Ang" = "앙"
"Nuden" = "누덴"
"Sobìr" = "소비르"
"Noram" = "노람"
"Bomel" = "보멜"
"Elbel" = "엘벨"
"Ennol" = "엔놀"
"Rirnöl" = "리르놀"
"Stemel" = "스테멜"
"Zìzcun" = "지즈쿤"
"Ebal" = "에발"
"Emdush" = "엠두쉬"
"Nanir" = "나니르"
"Irid" = "이리드"
"Dallith" = "달리스"
"Kìrar" = "키라르"
"Ethram" = "에스람"
"Neshast" = "네샤스트"
"Ibesh" = "이베쉬"
"Sûbil" = "수빌"
"Âbir" = "아비르"
"Omthel" = "옴셀"
"Istbar" = "이스트바르"
"Dumat" = "두마트"
"Lames" = "라메스"
"Lavath" = "라바스"
"Mözir" = "모지르"
"Relon" = "렐론"
"Notlith" = "노틀리스"
"Tithleth" = "티슬레스"
"Oten" = "오텐"
"Ikùl" = "이쿨"
"Bocash" = "보카쉬"
"Fenok" = "페노크"
"Etom" = "에톰"
"Mukar" = "무카르"
"Ekast" = "에카스트"
"Ushdish" = "우쉬디쉬"
"Zagug" = "자구그"
"Nabid" = "나비드"
"Sosh" = "소쉬"
"Gasìs" = "가시스"
"Vathem" = "바셈"
"Noglesh" = "노글레쉬"
"Nanul" = "나눌"
"Cudïst" = "쿠디스트"
"Kåtâk" = "카타크"
"Etvuth" = "에트부스"
"Kith" = "키스"
"Bêngeng" = "벤겡"
"Mishthem" = "미쉬셈"
"Girust" = "기루스트"
"Othlest" = "오슬레스트"
"Bubnus" = "부브누스"
"Igath" = "이가스"
"Ïthod" = "이소드"
"Aran" = "아란"
"Ûthir" = "우시르"
"Nekut" = "네쿠트"
"Emal" = "에말"
"Gathil" = "가실"
"Kitung" = "키퉁"
"Borlon" = "보를론"
"Ashmôn" = "아쉬몬"
"Uthmik" = "우스미크"
"Mostod" = "모스토드"
"Baktus" = "박투스"
"Idrom" = "이드롬"
"Istik" = "이스티크"
"Kafâsh" = "카파쉬"
"Ecosh" = "에코쉬"
"Eshom" = "에숌"
"Nesteth" = "네스테스"
"Thebil" = "세빌"
"Ammesh" = "아메쉬"
"Ral" = "랄"
"Guz" = "구즈"
"Reksas" = "렉사스"
"Nêcik" = "네시크"
"Elik" = "엘리크"
"Akmam" = "아크맘"
"Umstiz" = "움스티즈"
"Gecast" = "게카스트"
"Afen" = "아펜"
"Kúd" = "쿠드"
"Gansit" = "간시트"
"Fôker" = "포케르"
"Sakil" = "사킬"
"Lirér" = "리레르"
"Dezrem" = "데즈렘"
"Lanir" = "라니르"
"Est" = "에스트"
"Duz" = "두즈"
"Umar" = "우마르"
"Desis" = "데시스"
"Adag" = "아다그"
"Uben" = "우벤"
"Sesh" = "세쉬"
"Ngubmul" = "굽물"
"Azuz" = "아주즈"
"Bonun" = "보눈"
"Olthez" = "올세즈"
"Zunek" = "주네크"
"Lal" = "랄"
"Isak" = "이사크"
"Ganad" = "가나드"
"Kik" = "키크"
"Mïshak" = "미샤크"
"Omât" = "오마트"
"Soshor" = "소쇼르"
"Zakgol" = "자크골"
"Kekim" = "케킴"
"Ziksis" = "직시스"
"Adbok" = "아드보크"
"Tangak" = "탕가크"
"Bâsen" = "바센"
"Koman" = "코만"
"Vës" = "베스"
"Guthstak" = "구스타크"
"Vathsith" = "바시스"
"Stukón" = "스투콘"
"Tumos" = "투모스"
"Íkthag" = "익사그"
"Nulral" = "눌랄"
"Vuzded" = "부즈데드"
"Shagog" = "샤고그"
"Keng" = "켕"
"Gïnon" = "기논"
"Mëtin" = "메틴"
"Isan" = "이산"
"Rithog" = "리소그"
"Edan" = "에단"
"Gusgash" = "구스가쉬"
"Togal" = "토갈"
"Mot" = "모트"
"Vuknud" = "부크누드"
"Nefast" = "네파스트"
"Arceth" = "아르세스"
"Emen" = "에멘"
"Stin" = "스틴"
"Ibas" = "이바스"
"Othob" = "오소브"
"Rûl" = "룰"
"Idgag" = "이드가그"
"Ozor" = "오조르"
"Ibes" = "이베스"
"Moshnún" = "모쉬눈"
"Akuth" = "아쿠스"
"Ad" = "아드"
"Kulsim" = "쿨심"
"Tecàk" = "테카크"
"Kêshshak" = "케쉬샤크"
"Subet" = "수베트"
"Shazak" = "샤자크"
"Idith" = "이디스"
"Dubmen" = "두브멘"
"Rimad" = "리마드"
"Ongos" = "온고스"
"Shukar" = "슈카르"
"Ôsust" = "오수스트"
"Lasgan" = "라스간"
"Lerteth" = "레르테스"
"Timnär" = "팀나르"
"Zeg" = "제그"
"Kán" = "칸"
"Ugut" = "우구트"
"Nubam" = "누밤"
"Becor" = "베코르"
"Vudnis" = "부드니스"
"Ittás" = "이타스"
"Golast" = "골라스트"
"Selen" = "셀렌"
"Angzak" = "앙자크"
"Elis" = "엘리스"
"Kabat" = "카바트"
"Lïd" = "리드"
"Bot" = "보트"
"Akrul" = "아크룰"
"Kan" = "칸"
"Shaketh" = "샤케스"
"Mugshith" = "무그시스"
"Stïvut" = "스티부트"
"Mosos" = "모소스"
"Tangath" = "탕가스"
"Stëlmith" = "스텔미스"
"Bithsêst" = "비스세스트"
"Bobet" = "보베트"
"Dizesh" = "디제쉬"
"Ebbus" = "에부스"
"Tilesh" = "틸레쉬"
"Arin" = "아린"
"Atol" = "아톨"
"Ösir" = "오시르"
"Kasben" = "카스벤"
"Onget" = "온게트"
"Shetbêth" = "셰트베스"
"Eknar" = "엑나르"
"Isrir" = "이스리르"
"Cegol" = "세골"
"Gósmer" = "고스메르"
"Ticek" = "티세크"
"Itnet" = "이트네트"
"Morus" = "모루스"
"Íster" = "이스터"
"Othâsh" = "오사쉬"
"Kôkdath" = "콕다스"
"Distat" = "디스타트"
"Nan" = "난"
"Orngim" = "오른김"
"Nirur" = "니루르"
"Ozur" = "오주르"
"Sar" = "사르"
"Umäm" = "우맘"
"Zotthol" = "조트솔"
"Kiret" = "키레트"
"Govûl" = "고불"
"Thisrid" = "시스리드"
"Kizab" = "키자브"
"Oshot" = "오쇼트"
"Bisek" = "비세크"
"Mirstal" = "미르스탈"
"Lanzil" = "란질"
"Dëngstam" = "뎅스탐"
"Okosh" = "오코쉬"
"Munsog" = "문소그"
"Liruk" = "리루크"
"Geget" = "게게트"
"Vathez" = "바세즈"
"Îcum" = "이쿰"
"Detgash" = "데트가쉬"
"Adil" = "아딜"
"Lelum" = "렐룸"
"Sirab" = "시라브"
"Stelid" = "스텔리드"
"Isden" = "이스덴"
"Kussad" = "쿠사드"
"Rithlut" = "리슬루트"
"Onul" = "오눌"
"Othil" = "오실"
"Limâr" = "리마르"
"Edól" = "에돌"
"Sital" = "시탈"
"Kathil" = "카실"
"Ken" = "켄"
"Estil" = "에스틸"
"Rikkir" = "리키르"
"Volal" = "볼랄"
"Lish" = "리쉬"
"Omrist" = "옴리스트"
"Ud" = "우드"
"Othôs" = "오소스"
"Num" = "눔"
"Dosîm" = "도심"
"Lim" = "림"
"Nentuk" = "넨투크"
"Anur" = "아누르"
"Lolum" = "롤룸"
"Il" = "일"
"Bumal" = "부말"
"Soloz" = "솔로즈"
"Cugshil" = "쿠그실"
"Duthal" = "두살"
"Lêrush" = "레루쉬"
"Åm" = "암"
"Inol" = "이놀"
"Ging" = "깅"
"Rilem" = "릴렘"