base = "dwarf_language::veb"

[[rulesets]]
name = "main"
[rulesets.rules]
"Bidok" = "비도크"
"Anam" = "아남"
"Asrer" = "아스레르"
"Fidgam" = "피드감"
"Rashgur" = "라쉬구르"
"Ardes" = "아르데스"
"Geshak" = "게샤크"
"Nel" = "넬"
"Olmul" = "올물"
"Mìshos" = "미쇼스"
"Dolush" = "돌루쉬"
"Ritan" = "리탄"
"Enir" = "에니르"
"Oshnïl" = "오쉬닐"
"Estun" = "에스툰"
"Nitig" = "니티그"
"Nulom" = "눌롬"
"Enoz" = "에노즈"
"Sákrith" = "사크리스"
"Satneng" = "사트넹"
"Sut" = "수트"
"Rotig" = "로티그"
"Rifot" = "리포트"
"Âtrid" = "아트리드"
"Umer" = "우메르"
"Gåkïz" = "가키즈"
"Themor" = "세모르"
"Alåth" = "알라스"
"Atêk" = "아테크"
"Selsten" = "셀스텐"
"Shomad" = "쇼마드"
"Othsin" = "오신"
"Ùst" = "우스트"
"Okab" = "오카브"
"Sazir" = "사지르"
"Lek" = "레크"
"Stumäm" = "스투맘"
"Rozsed" = "로즈세드"
"Enshal" = "엔샬"
"Nïng" = "닝"
"Instol" = "인스톨"
"Ostar" = "오스타르"
"Stal" = "스탈"
"Sidos" = "시도스"
"Ethbesh" = "에스베쉬"
"Idos" = "이도스"
"Ogîk" = "오지크"
"Ozkak" = "오즈카크"
"Åkum" = "오쿰"
"Nastid" = "나스티드"
"Nicat" = "니카트"
"Tenshed" = "텐셰드"
"Catten" = "카텐"
"Onshen" = "온셴"
"Sid" = "시드"
"Ìtdùn" = "이툰"
"Emad" = "에마드"
"Zursùl" = "주르술"
"Îtat" = "이타트"
"Dib" = "디브"
"Oril" = "오릴"
"Bukog" = "부코그"
"Atot" = "아토트"
"Imik" = "이미크"
"Rag" = "라그"
"Merig" = "메리그"
"Lisid" = "리시드"
"Dodók" = "도도크"
"Fushur" = "푸슈르"
"Gast" = "가스트"
"Egast" = "에가스트"
"Akgos" = "아코스"
"Élmeth" = "엘메스"
"Avéd" = "아베드"
"Oddom" = "오돔"
"Zatam" = "자탐"
"Shatag" = "샤타그"
"Sholid" = "쇼리드"
"Om" = "옴"
"Balad" = "발라드"
"Dakas" = "다카스"
"Zoluth" = "졸루스"
"Mulåsh" = "물라쉬"
"Tusung" = "투숭"
"Egul" = "에굴"
"Rafar" = "라파르"
"Amkol" = "암콜"
"Laltur" = "랄투르"
"Rigòth" = "리고스"
"Dunan" = "두난"
"Shadkik" = "샤드키크"
"Than" = "산"
"Memrut" = "멤루트"
"Usal" = "우살"
"Ôm" = "옴"
"Cagith" = "카기스"
"Deshlir" = "데슐리르"
"Avum" = "아붐"
"Matul" = "마툴"
"Irtir" = "이르티르"
"Rutod" = "루토드"
"Lodel" = "로델"
"Ag" = "아그"
"Kodor" = "코도르"
"Råsh" = "라쉬"
"Ros" = "로스"
"Galthor" = "갈소르"
"Ub" = "우브"
"Ôtthat" = "오사트"
"Ozleb" = "오즐레브"
"Thazor" = "사조르"
"Etath" = "에타스"
"Gingim" = "긴김"
"Shoduk" = "쇼두크"
"Birir" = "비리르"
"Lozlok" = "로즐로크"
"Fak" = "파크"
"Ogon" = "오곤"
"Avog" = "아보그"
"Zag" = "자그"
"Monang" = "모낭"
"Thosbut" = "소스부트"
"Ór" = "오르"
"Sub" = "수브"
"Sterus" = "스테루스"
"Addor" = "아도르"
"Asdûg" = "아스두그"
"Zin" = "진"
"Åmmeb" = "오메브"
"Kokeb" = "코케브"
"Deb" = "데브"
"Sárek" = "사레크"
"Lushôn" = "루숀"
"Mizês" = "미제스"
"Sefol" = "세폴"
"Ramtak" = "람타크"
"Onrel" = "온렐"
"Ruzos" = "루조스"
"Ildom" = "일돔"
"Umid" = "우미드"
"Nefek" = "네페크"
"Ivom" = "이봄"
"Thiz" = "시즈"
"Roduk" = "로두크"
"Bardum" = "바르둠"
"Atöl" = "아톨"
"Ngitkar" = "니트카르"
"Lesast" = "레사스트"
"Asiz" = "아시즈"
"Sofûsh" = "소푸쉬"
"Ëtul" = "에툴"
"Låluth" = "랄루스"
"Ireg" = "이레그"
"Gigin" = "기긴"
"Atham" = "아삼"
"Atul" = "아툴"
"Ìltang" = "일탕"
"Dumed" = "두메드"
"Ézneth" = "에즈네스"
"Tiklom" = "티클롬"
"Ïsir" = "이시르"
"Gishdist" = "기쉬디스트"
"Kèbmak" = "케브마크"
"Egen" = "에겐"
"Fikod" = "피코드"
"Almôsh" = "알모쉬"
"Bavast" = "바바스트"
"Kåtdir" = "카티르"
"Éthes" = "에세스"
"Igest" = "이게스트"
"Desgir" = "데스기르"
"Ugzol" = "우그졸"
"Îgam" = "이감"
"Gommuk" = "고무크"
"Nerrid" = "네리드"
"Zágod" = "자고드"
"Tomêm" = "토멤"
"Bol" = "볼"
"Ûz" = "우즈"
"Duthnur" = "두스누르"
"Sodzul" = "소드줄"
"Ïlun" = "이룬"
"Râluk" = "랄루크"
"Shameb" = "샤메브"
"Ûd" = "우드"
"Dumur" = "두무르"
"Kunon" = "쿠논"
"Lilum" = "릴룸"
"Ikus" = "이쿠스"
"Enur" = "에누르"
"Kur" = "쿠르"
"Thibam" = "시밤"
"Vostaz" = "보스타즈"
"Stòkïd" = "스토키드"
"Meb" = "메브"
"Lumen" = "루멘"
"Etas" = "에타스"
"Maton" = "마톤"
"Zatthud" = "자수드"
"Abol" = "아볼"
"Mâtzang" = "마트장"
"Ilned" = "일네드"
"Vagúsh" = "바구쉬"
"Alis" = "알리스"
"Inshot" = "인쇼트"
"Arzes" = "아르제스"
"Äbor" = "아보르"
"Kûbuk" = "쿠부크"
"Meng" = "멩"
"Anban" = "안반"
"Erar" = "에라르"
"Tagùz" = "타구즈"
"Omtäl" = "옴탈"
"Gabet" = "가베트"
"Âmid" = "아미드"
"Thak" = "사크"
"Uvar" = "우바르"
"Ìnal" = "이날"
"Gukil" = "구킬"
"Lektad" = "렉타드"
"Dimol" = "디몰"
"Lised" = "리세드"
"Muzish" = "무지쉬"
"Kôn" = "콘"
"An" = "안"
"Lar" = "라르"
"Kalal" = "칼랄"
"Nalthish" = "날티쉬"
"Rimuk" = "리무크"
"Avuz" = "아부즈"
"Ònul" = "오눌"
"Odgúb" = "오드굽"
"Ushlub" = "우슐루브"
"Adesh" = "아데쉬"
"Usân" = "우산"
"Kez" = "케즈"
"Ikûl" = "이쿨"
"Semtom" = "셈톰"
"Necak" = "네카크"
"Kezol" = "케졸"
"Umel" = "우멜"
"Eddud" = "에두드"
"Am" = "암"
"Sanreb" = "산레브"
"Shigós" = "쉬고스"
"Âgez" = "아게즈"
"Iden" = "이덴"
"Mörul" = "모룰"
"Logem" = "로겜"
"Lerom" = "레롬"
"Tetthush" = "테트슈"
"Thimshur" = "심슈르"
"Adas" = "아다스"
"Ilrom" = "일롬"
"Thet" = "세트"
"Shithath" = "시사스"
"Sokan" = "소칸"
"Ison" = "이손"
"Erok" = "에로크"
"Stisträs" = "스티스트라스"
"Îm" = "임"
"Tathtat" = "타스타트"
"Shoner" = "쇼네르"
"Idok" = "이도크"
"Ïtsas" = "이츠사스"
"Zoz" = "조즈"
"Mubun" = "무분"
"Teshkad" = "테쉬카드"
"Gashcoz" = "가쉬코즈"
"Kasith" = "카시스"
"Tashem" = "타솀"
"Iseth" = "이세스"
"Imsal" = "임살"
"Borush" = "보루쉬"
"Umoz" = "우모즈"
"Vudthar" = "부드사르"
"Stigaz" = "스티가즈"
"Ograd" = "오그라드"
"Ikud" = "이쿠드"
"Memad" = "메마드"
"Eshik" = "에쉬크"
"Inem" = "이넴"
"Akir" = "아키르"
"Nokgol" = "노크골"
"Athel" = "아셀"
"Seng" = "셍"
"Ethab" = "에사브"
"Locun" = "로쿤"
"Orrun" = "오르룬"
"Lulâr" = "룰라르"
"Luzat" = "루자트"
"Suthån" = "수산"
"Ilid" = "일리드"
"Rur" = "루르"
"Sashas" = "사샤스"
"Belar" = "벨라르"
"Laz" = "라즈"
"Urrïth" = "우리스"
"Kikës" = "키케스"
"Gudas" = "구다스"
"Tokthat" = "토크사트"
"Ubas" = "우바스"
"Tathur" = "타수르"
"Givel" = "기벨"
"Absam" = "아브삼"
"Genlath" = "겐라스"
"Asol" = "아솔"
"Esdor" = "에스도르"
"Zursul" = "주르술"
"Bithit" = "비시트"
"Lêned" = "레네드"
"Sodel" = "소델"
"Ônam" = "오남"
"Otung" = "오퉁"
"Keskal" = "케스칼"
"Tomus" = "토무스"
"Dugan" = "두간"
"Nåst" = "노스트"
"Mesir" = "메시르"
"Éth" = "에스"
"Zokun" = "조쿤"
"Osal" = "오살"
"Mosol" = "모솔"
"Udesh" = "우데쉬"
"Dakäl" = "다칼"
"Sezuk" = "세주크"
"Megid" = "메기드"
"Themthir" = "셈시르"
"Tekmok" = "테크모크"
"Îlkeb" = "일케브"
"Tob" = "토브"
"Kal" = "칼"
"Zeber" = "제베르"
"Geles" = "겔레스"
"Ostuk" = "오스투크"
"Magel" = "마겔"
"Umåm" = "우맘"
"Bûnem" = "부넴"
"Vod" = "보드"
"Kebul" = "케불"
"Âm" = "암"
"Esesh" = "에세쉬"
"Tishis" = "티시스"
"Rulush" = "룰루쉬"
"Usur" = "우수르"
"Kob" = "코브"
"Magak" = "마가크"
"Imesh" = "이메쉬"
"Noböt" = "노보트"
"Dugud" = "두구드"
"Ulåb" = "울라브"
"Zat" = "자트"
"Oltud" = "올투드"
"Savot" = "사보트"
"Kot" = "코트"
"Shìstsak" = "시스트사크"
"Risid" = "리시드"
"Ecut" = "에쿠트"
"Tôsed" = "토세드"
"Nîles" = "닐레스"
"Rêg" = "레그"
"Äkig" = "아키그"
"Abod" = "아보드"
"Sat" = "사트"
"Fûbeg" = "푸베그"
"Tunur" = "투누르"
"Eb" = "에브"
"Oceg" = "오세그"
"Imgoz" = "임고즈"
"Mozib" = "모지브"
"Êlbem" = "엘벰"
"Sined" = "시네드"
"Ronush" = "로누쉬"
"Urmim" = "우르밈"
"Enkos" = "엔코스"
"Masos" = "마소스"
"Vetek" = "베테크"
"Thilség" = "실세그"
"Stettad" = "스테타드"
"Amal" = "아말"
"Asteb" = "아스테브"
"Okil" = "오킬"
"Gelut" = "겔루트"
"Arros" = "아로스"
"Amud" = "아무드"
"Tan" = "탄"
"Bal" = "발"
"Dostust" = "도스투스트"
"Tat" = "타트"
"Nish" = "니쉬"
"Kälán" = "칼란"
"Rìthar" = "리사르"
"Ïggal" = "이갈"
"Datlad" = "다틀라드"
"Vafig" = "바피그"
"Esis" = "에시스"
"Kobem" = "코벰"
"Gamil" = "가밀"
"Cavor" = "카보르"
"Segun" = "세군"
"Ód" = "오드"
"Nilim" = "닐림"
"Gim" = "짐"
"Semor" = "세모르"
"Bakust" = "바쿠스트"
"Gutid" = "구티드"
"Tudrug" = "투드루그"
"Ronstiz" = "론스티즈"
"Amluth" = "암루스"
"Tost" = "토스트"
"Okol" = "오콜"
"Nursher" = "누르셰르"
"Rodim" = "로딤"
"Berdan" = "베르단"
"Ngesgäs" = "네스게스"
"Legon" = "레곤"
"Zalìs" = "잘리스"
"Nisûn" = "니순"
"Lidod" = "리도드"
"Azin" = "아진"
"Uker" = "우케르"
"Nilun" = "닐룬"
"Orshar" = "오르샤르"
"Sibnir" = "시브니르"
"Kol" = "콜"
"Bomrek" = "봄레크"
"Boket" = "보케트"
"Iklist" = "이클리스트"
"Shos" = "쇼스"
"Oslan" = "오슬란"
"Lakàl" = "라칼"
"Rôber" = "로베르"
"Nabår" = "나보르"
"Kulal" = "쿨랄"
"Ducim" = "두심"
"Shoshin" = "쇼신"
"Ulzest" = "울제스트"
"Taron" = "타론"