base = "adv::claim"

[[rulesets]]
[rulesets.rules]
"Claim {name}{direction} as pet" = "{name}{direction}(을)를 반려동물로 지정"

[[rulesets]]
name = "name"
[rulesets.rules]
"{::creatures::caste::name}" = "{::creatures::caste::name}"

[[rulesets]]
name = "direction"
optional = true
[rulesets.rules]
"{::adv::direction}" = "{::adv::direction}"