base = "english_name::adj"

[[rulesets]]
name = "main"
[rulesets.rules]
"Abated" = "완화된"
"Absolute" = "절대적인"
"Abysmal" = "끔찍한"
"Abyssal" = "심연"
"Accidental" = "우연한"
"Ace" = "일류"
"Aching" = "쑤시는"
"Acrid" = "매캐한"
"Admired" = "칭송받는"
"Adorable" = "사랑스러운"
"Adventurous" = "모험적인"
"Afflicted" = "고통받는"
"Ageless" = "늙지 않는"
"Alchemical" = "연금술"
"Allied" = "동맹"
"Amazing" = "놀라운"
"Amber" = "호박색"
"Ambiguous" = "모호한"
"Amethyst" = "자수정빛"
"Amusing" = "재미있는"
"Ancient" = "고대"
"Angelic" = "천사"
"Angry" = "성난"
"Anguished" = "고뇌하는"
"Aqua" = "물빛"
"Aquamarine" = "청록빛"
"Ardent" = "열렬한"
"Armored" = "무장한"
"Artificial" = "인공적인"
"Ashen" = "잿빛"
"Ashamed" = "부끄러운"
"Assaulted" = "공격받은"
"Auburn" = "적갈색"
"Autonomous" = "자율적인"
"Autumnal" = "가을"
"Awe-Inspiring" = "경외로운"
"Azure" = "창공"
"Bad" = "나쁜"
"Balanced" = "균형 잡힌"
"Bald" = "대머리"
"Banded" = "줄무늬 있는"
"Barbarous" = "야만적인"
"Barricaded" = "봉쇄된"
"Basic" = "기본적인"
"Bearded" = "수염 난"
"Beautiful" = "아름다운"
"Beige" = "베이지색"
"Beloved" = "사랑받는"
"Belted" = "띠를 두른"
"Bent" = "구부러진"
"Bewildering" = "당혹스러운"
"Bewitched" = "마법에 걸린"
"Big" = "큰"
"Born" = "태어난"
"Bitter" = "쓴"
"Black" = "검은"
"Blameless" = "결백한"
"Blanketed" = "뒤덮인"
"Blighted" = "병든"
"Blind" = "눈먼"
"Bloated" = "부어오른"
"Blockaded" = "차단된"
"Bloody" = "피투성이"
"Blotted" = "얼룩진"
"Blowing" = "부는"
"Blue" = "푸른"
"Blunt" = "무딘"
"Bold" = "대담한"
"Boring" = "지루한"
"Boyish" = "소년 같은"
"Braided" = "땋은"
"Branded" = "낙인찍힌"
"Brash" = "건방진"
"Brass" = "황동빛"
"Brave" = "용감한"
"Brazen" = "뻔뻔한"
"Bridled" = "굴레를 쓴"
"Bright" = "밝은"
"Brilliant" = "찬란한"
"Bronze" = "청동빛"
"Brown" = "갈색"
"Brushed" = "솔질된"
"Brutal" = "잔혹한"
"Buff" = "담황색"
"Bulbous" = "볼록한"
"Busy" = "바쁜"
"Buttery" = "버터 같은"
"Calamitous" = "재앙"
"Calm" = "고요한"
"Cardinal" = "진홍색"
"Carmine" = "양홍색"
"Carnal" = "육욕"
"Cavernous" = "동굴 같은"
"Celebrated" = "이름난"
"Certain" = "확실한"
"Cerulean" = "짙은 푸른색"
"Charcoal" = "숯빛"
"Chartreuse" = "연두색"
"Chaste" = "순결한"
"Cheerful" = "쾌활한"
"Chestnut" = "밤색"
"Chocolate" = "초콜릿색"
"Chunky" = "두툼한"
"Cinnamon" = "계피색"
"Circular" = "원형"
"Circumstantial" = "정황적인"
"Clean" = "깨끗한"
"Clear" = "맑은"
"Climactic" = "절정"
"Closed" = "닫힌"
"Cloudy" = "구름 낀"
"Coastal" = "해안"
"Cobalt" = "코발트색"
"Coincidental" = "우연"
"Cold" = "차가운"
"Colorless" = "무색"
"Combined" = "결합된"
"Comedic" = "희극적인"
"Common" = "흔한"
"Competitive" = "경쟁적인"
"Complex" = "복잡한"
"Confident" = "자신감 있는"
"Confining" = "가두는"
"Confusing" = "혼란스러운"
"Connected" = "연결된"
"Considerate" = "사려 깊은"
"Constructive" = "건설적인"
"Contained" = "갇힌"
"Contemptible" = "경멸스러운"
"Contested" = "다투는"
"Contingent" = "우발적인"
"Convenient" = "편리한"
"Cooperative" = "협조적인"
"Copper" = "구릿빛"
"Corrupt" = "타락한"
"Courageous" = "용기 있는"
"Courteous" = "예의 바른"
"Cracked" = "갈라진"
"Cradled" = "감싸인"
"Craterous" = "분화구투성이"
"Crazed" = "미친"
"Crazy" = "정신 나간"
"Creamy" = "크림 같은"
"Creative" = "창의적인"
"Creepy" = "오싹한"
"Cremated" = "화장된"
"Crested" = "볏이 있는"
"Crewed" = "탑승한"
"Crimson" = "심홍색"
"Cross" = "엇갈린"
"Crowded" = "붐비는"
"Cruel" = "잔인한"
"Crystalline" = "수정 같은"
"Cunning" = "교활한"
"Curious" = "호기심 많은"
"Curled" = "말린"
"Cyclopean" = "거대한"
"Dabbling" = "물장구치는"
"Dangerous" = "위험한"
"Dank" = "축축한"
"Dark" = "어두운"
"Dead" = "죽은"
"Dear" = "소중한"
"Decent" = "점잖은"
"Decisive" = "단호한"
"Declining" = "쇠퇴하는"
"Deep" = "깊은"
"Defective" = "결함 있는"
"Defended" = "방어된"
"Defensive" = "방어적인"
"Deferent" = "경의를 표하는"
"Deified" = "신격화된"
"Delightful" = "즐거운"
"Dented" = "움푹 팬"
"Depressed" = "우울한"
"Destined" = "운명 지어진"
"Deteriorated" = "악화된"
"Deviant" = "일탈"
"Devious" = "기만적인"
"Diamond" = "다이아몬드"
"Dignified" = "위엄 있는"
"Dim" = "어스레한"
"Diminished" = "감소된"
"Dimpled" = "보조개 있는"
"Dipped" = "담긴"
"Disemboweled" = "내장이 파열된"
"Disgusting" = "역겨운"
"Dishonest" = "정직하지 못한"
"Disloyal" = "불충한"
"Dismal" = "음울한"
"Dispersed" = "흩어진"
"Distant" = "먼"
"Distinct" = "뚜렷한"
"Distracting" = "산만한"
"Divine" = "신성한"
"Domestic" = "길들여진"
"Dominant" = "지배적인"
"Doomed" = "파멸할 운명의"
"Dour" = "시무룩한"
"Doused" = "흠뻑 젖은"
"Drab" = "칙칙한"
"Dreadful" = "끔찍한"
"Dreamy" = "꿈결 같은"
"Drenched" = "흠뻑 젖은"
"Droopy" = "축 늘어진"
"Dull" = "무딘"
"Dutiful" = "충실한"
"Dwindling" = "줄어드는"
"Early" = "이른"
"Earthen" = "흙으로 된"
"East" = "동쪽"
"Ecru" = "황갈색"
"Eerie" = "기괴한"
"Elder" = "원로"
"Elevated" = "높아진"
"Emancipated" = "해방된"
"Embraced" = "품에 안긴"
"Emerald" = "에메랄드빛"
"Empty" = "빈"
"Enchanted" = "마법에 걸린"
"Enjoyable" = "즐거운"
"Entangled" = "얽힌"
"Entrancing" = "매혹적인"
"Epidemic" = "유행성"
"Equal" = "동등한"
"Equivalent" = "상응하는"
"Erased" = "지워진"
"Escorted" = "호위받는"
"Esteemed" = "존경받는"
"Eternal" = "영원한"
"Euphoric" = "크게 기뻐하는"
"Evaporated" = "증발한"
"Even" = "고른"
"Everlasting" = "변치 않는"
"Everseeing" = "항상 지켜보는"
"Evil" = "사악한"
"Eviscerated" = "내장이 빼내진"
"Exalted" = "고귀한"
"Excavated" = "발굴된"
"Fabulous" = "전설적인"
"Factional" = "파벌"
"Faded" = "빛바랜"
"Failed" = "실패한"
"Faint" = "희미한"
"Fair (color)" = "밝은"
"Fair (even)" = "공정한"
"Faithful" = "충실한"
"FALSE" = "거짓된"
"Famous" = "유명한"
"Familial" = "가족"
"Fancy" = "화려한"
"Fat" = "뚱뚱한"
"Fatal" = "치명적인"
"Fated" = "운명 지어진"
"Fed" = "배부른"
"Fell" = "잔인한"
"Fenced" = "울타리 쳐진"
"Feral" = "야생"
"Ferocious" = "사나운"
"Festive" = "축제"
"Fetid" = "악취 나는"
"Feverish" = "열띤"
"Fierce" = "맹렬한"
"Fiery" = "불타는"
"First" = "첫 번째"
"Flaxen" = "아마빛"
"Flayed" = "가죽이 벗겨진"
"Flecked" = "얼룩덜룩한"
"Fleshy" = "살집이 있는"
"Flickering" = "깜박이는"
"Flighty" = "변덕스러운"
"Flimsy" = "얄팍한"
"Flowery" = "꽃피는"
"Foggy" = "안개 낀"
"Folded" = "접힌"
"Fondled" = "어루만져진"
"Foolish" = "어리석은"
"Fortuitous" = "우연한"
"Fortunate" = "운 좋은"
"Fragile" = "연약한"
"Fragrant" = "향기로운"
"Free" = "자유로운"
"Fresh" = "신선한"
"Friendly" = "친근한"
"Frightful" = "무서운"
"Frigid" = "몹시 추운"
"Frilly" = "프릴이 달린"
"Frosty" = "서리 내린"
"Frothy" = "거품 많은"
"Fruity" = "과일 향 나는"
"Fuchsia" = "자홍색"
"Full" = "가득 찬"
"Furious" = "격렬한"
"Future" = "미래"
"Garish" = "지나치게 화려한"
"Gaunt" = "수척한"
"Geared" = "장비를 갖춘"
"Gilded" = "금박을 입힌"
"Girdled" = "띠를 두른"
"Girlish" = "소녀 같은"
"Glacial" = "빙하"
"Glad" = "기쁜"
"Gleeful" = "신이 난"
"Glittery" = "반짝이는"
"Gloomy" = "침울한"
"Glorious" = "영광스러운"
"Gloved" = "장갑을 낀"
"Glowing" = "빛나는"
"Glum" = "우울한"
"Gnarled" = "비틀린"
"Godly" = "신성한"
"God-Forsaken" = "신에게 버림받은"
"Golden" = "황금빛"
"Goldenrod" = "황금꽃색"
"Good" = "좋은"
"Gory" = "피투성이"
"Grand" = "웅장한"
"Granite" = "화강암"
"Grasping" = "움켜쥐는"
"Gray" = "회색"
"Great" = "위대한"
"Greater" = "더 위대한"
"Greatest" = "가장 위대한"
"Green" = "녹색"
"Grieving" = "슬퍼하는"
"Grim" = "암울한"
"Gristly" = "질긴"
"Grizzly" = "회백색"
"Grooved" = "홈이 파인"
"Gross" = "징그러운"
"Guilty" = "유죄"
"Habitual" = "습관적인"
"Hairy" = "털이 많은"
"Hale" = "건강한"
"Handy" = "유용한"
"Hardy" = "강인한"
"Harmonious" = "조화로운"
"Harsh" = "가혹한"
"Hateful" = "증오하는"
"Hazy" = "아득한"
"Healing" = "치유하는"
"Hot" = "뜨거운"
"Heavenly" = "천상"
"Heavy" = "무거운"
"Heliotrope" = "연보라색"
"Hellish" = "지옥 같은"
"Helmed" = "투구를 쓴"
"Helpful" = "도움이 되는"
"Hermitic" = "은둔하는"
"Heroic" = "영웅적인"
"Hideous" = "흉측한"
"High" = "높은"
"Hoary" = "백발"
"Held" = "잡힌"
"Hollow" = "속이 빈"
"Holy" = "신성한"
"Homely" = "소박한"
"Honest" = "정직한"
"Honorable" = "명예로운"
"Hopeful" = "희망찬"
"Humble" = "겸손한"
"Humid" = "습한"
"Humorous" = "유머러스한"
"Hungry" = "굶주린"
"Icy" = "얼음 같은"
"Idle" = "게으른"
"Ignited" = "점화된"
"Ignoble" = "비천한"
"Ignorant" = "무지한"
"Ill" = "병든"
"Immoral" = "부도덕한"
"Immortal" = "불멸"
"Imperial" = "제국"
"Impervious" = "불침투성의"
"Imprisoned" = "수감된"
"Impure" = "불순한"
"Incidental" = "부수적인"
"Incinerated" = "소각된"
"Inconsiderate" = "배려심 없는"
"Inconvenient" = "불편한"
"Indigo" = "남색"
"Infallible" = "틀림없는"
"Infamous" = "악명 높은"
"Infected" = "감염된"
"Inferior" = "열등한"
"Infinite" = "무한한"
"Influential" = "영향력 있는"
"Inky" = "먹물 같은"
"Innocent" = "순결한"
"Insensitive" = "둔감한"
"Insightful" = "통찰력 있는"
"Intense" = "강렬한"
"Intricate" = "복잡한"
"Invisible" = "보이지 않는"
"Ivory" = "상아색"
"Jade" = "옥빛"
"Jaundiced" = "황달 걸린"
"Bejeweled" = "보석으로 장식된"
"Joyous" = "기쁜"
"Just" = "공정한"
"Kindled" = "불붙은"
"Kind" = "친절한"
"Know" = "아는"
"Laborious" = "힘든"
"Labyrinthine" = "미로 같은"
"Lacy" = "레이스 달린"
"Laconic" = "간결한"
"Lamented" = "애도하는"
"Languishing" = "시들어가는"
"Lardy" = "비계가 많은"
"Large" = "거대한"
"Larval" = "애벌레"
"Last" = "마지막"
"Late" = "늦은"
"Lauded" = "칭송받는"
"Lavender" = "연보라빛"
"Lazy" = "게으른"
"Leafy" = "잎이 무성한"
"Leaky" = "새는"
"Lean" = "마른"
"Learned" = "학식 있는"
"Least" = "가장 작은"
"Legendary" = "전설적인"
"Lessened" = "감소된"
"Lesser" = "하급"
"Living" = "살아있는"
"Light" = "가벼운"
"Limp" = "축 처진"
"Lined" = "주름진"
"Little" = "작은"
"Livid" = "격노한"
"Lone" = "홀로인"
"Lonely" = "외로운"
"Lonesome" = "고독한"
"Long" = "긴"
"Lost" = "잃어버린"
"Lovely" = "사랑스러운"
"Low" = "낮은"
"Loyal" = "충성스러운"
"Lucid" = "명료한"
"Lucky" = "운 좋은"
"Lurid" = "소름 끼치는"
"Lush" = "무성한"
"Lustful" = "음탕한"
"Lustrous" = "윤이 나는"
"Luxurious" = "사치스러운"
"Lyrical" = "서정적인"
"Magical" = "마법"
"Mahogany" = "마호가니색"
"Malicious" = "악의적인"
"Malign" = "해로운"
"Maligned" = "비방받는"
"Malignant" = "악성의"
"Malodorous" = "악취 나는"
"Mangy" = "옴에 걸린"
"Maroon" = "적갈색"
"Massive" = "거대한"
"Matched (opposed)" = "맞서는"
"Matched (equal)" = "맞먹는"
"Mauve" = "연보라색"
"Mean (low)" = "비천한"
"Mean (nasty)" = "비열한"
"Meandering" = "구불구불한"
"Mechanical" = "기계"
"Mellow" = "부드러운"
"Merged" = "병합된"
"Messianic" = "구세주"
"Mighty" = "강력한"
"Mindful" = "염두에 두는"
"Mint" = "민트색"
"Mired" = "수렁에 빠진"
"Mirthful" = "유쾌한"
"Mischievous" = "장난기 많은"
"Misty" = "안개 낀"
"Modest" = "겸손한"
"Moist" = "촉촉한"
"Molten" = "녹아내린"
"Momentous" = "중대한"
"Monstrous" = "괴물 같은"
"Moral" = "도덕적인"
"Morose" = "시무룩한"
"Mortal" = "필멸"
"Mortified" = "굴욕적인"
"Most" = "가장 많은"
"Mountainous" = "산이 많은"
"Mournful" = "애절한"
"Mousy" = "소심한"
"Mucous" = "점액질"
"Muddled" = "혼란스러운"
"Muddy" = "진흙투성이의"
"Murky" = "탁한"
"Muscular" = "근육질"
"Musical" = "음악적인"
"Musty" = "퀴퀴한"
"Mute" = "무언"
"Mysterious" = "신비로운"
"Mythical" = "신화적인"
"Named" = "이름 지어진"
"Narrow" = "좁은"
"Nasty" = "더러운"
"National" = "국가"
"Natural" = "자연"
"Naughty" = "말썽꾸러기인"
"Negative" = "부정적인"
"Neutral" = "중립적인"
"New" = "새로운"
"Noble" = "고귀한"
"Noiseless" = "소리 없는"
"North" = "북쪽"
"Notched" = "톱니 모양의"
"Nourishing" = "영양분 있는"
"Null" = "무효"
"Oaken" = "참나무"
"Obeisant" = "정중한"
"Obscene" = "음란한"
"Obscure" = "모호한"
"Occult" = "비밀스러운"
"Oceanic" = "대양"
"Ochre" = "황토색"
"Odorous" = "냄새 나는"
"Oily" = "기름진"
"Old" = "오래된"
"Olive" = "올리브색"
"Ominous" = "불길한"
"Oracular" = "신탁"
"Ordered" = "정돈된"
"Organized" = "조직적인"
"Outrageous" = "터무니없는"
"Padded" = "패드를 댄"
"Painful" = "고통스러운"
"Pale" = "창백한"
"Parched" = "바싹 마른"
"Passionate" = "열정적인"
"Past" = "과거"
"Patterned" = "무늬 있는"
"Peaceful" = "평화로운"
"Perfect" = "완벽한"
"Permanent" = "영구적인"
"Perplexing" = "당혹스러운"
"Persuasive" = "설득력 있는"
"Pink" = "분홍색"
"Plain" = "평범한"
"Plaited" = "땋은"
"Plated" = "장갑을 댄"
"Playful" = "장난스러운"
"Pleated" = "주름진"
"Poetic" = "시적인"
"Pointy" = "뾰족한"
"Poisoned" = "중독된"
"Polished" = "광택 나는"
"Ponderous" = "육중한"
"Portentous" = "불길한"
"Praised" = "칭송받는"
"Pregnant" = "임신한"
"Present" = "현재"
"Prestigious" = "명성 있는"
"Prim" = "단정한"
"Prime" = "주요한"
"Primitive" = "원시적인"
"Pristine" = "원래 그대로의"
"Problematic" = "문제가 있는"
"Profane" = "불경스러운"
"Puce" = "검붉은"
"Pulpy" = "걸쭉한"
"Pungent" = "톡 쏘는"
"Pure" = "순수한"
"Purged" = "정화된"
"Purple" = "보라색"
"Putrid" = "악취 나는"
"Puzzling" = "당혹스러운"
"Quick" = "빠른"
"Quiescent" = "조용한"
"Quiet" = "고요한"
"Radiant" = "빛나는"
"Rainy" = "비 오는"
"Rancorous" = "원한 품은"
"Random" = "무작위"
"Rank" = "악취 나는"
"Rapid" = "빠른"
"Rare" = "희귀한"
"Raw" = "날것"
"Reclusive" = "은둔하는"
"Red" = "붉은"
"Regal" = "제왕"
"Released" = "풀려난"
"Relieved" = "안도하는"
"Remarkable" = "놀라운"
"Renowned" = "명성 있는"
"Reputed" = "평판이 있는"
"Respectful" = "공손한"
"Responsible" = "책임감 있는"
"Reticent" = "과묵한"
"Revered" = "존경받는"
"Revolting" = "역겨운"
"Rhyming" = "운율을 맞춘"
"Rhythmic" = "리듬감 있는"
"Riddled" = "구멍 뚫린"
"Righteous" = "정의로운"
"Ripe" = "익은"
"Risky" = "위험한"
"Roasted" = "구운"
"Robust" = "탄탄한"
"Romantic" = "낭만적인"
"Roomy" = "널찍한"
"Rosy" = "장밋빛"
"Rough" = "거친"
"Round" = "둥근"
"Rounded" = "둥글게 된"
"Routed" = "패주한"
"Royal" = "왕"
"Ruined" = "폐허가 된"
"Rumored" = "소문난"
"Russet" = "황갈색"
"Rustic" = "소박한"
"Ruthless" = "무자비한"
"Sable" = "검은빛"
"Sacrificial" = "희생"
"Sad" = "슬픈"
"Safe" = "안전한"
"Saffron" = "사프란색"
"Sagging" = "축 처진"
"Salty" = "짭짤한"
"Sandaled" = "샌들을 신은"
"Satiny" = "매끄러운"
"Saturnine" = "음침한"
"Savage" = "야만적인"
"Scabrous" = "딱지 앉은"
"Scalded" = "화상 입은"
"Scaly" = "비늘 덮인"
"Scandalous" = "수치스러운"
"Scarce" = "희소한"
"Scarlet" = "진홍색"
"Scholarly" = "학구적인"
"Scintillating" = "번뜩이는"
"Scorching" = "타는 듯한"
"Scoured" = "닳아 없어진"
"Scraped" = "긁힌"
"Scrubbed" = "문질러 씻은"
"Sculpted" = "조각된"
"Searing" = "타오르는"
"Secretive" = "비밀스러운"
"Sensitive" = "민감한"
"Sensual" = "관능적인"
"Sepia" = "암갈색"
"Severe" = "가혹한"
"Shady" = "그늘진"
"Shaken" = "흔들린"
"Shameful" = "수치스러운"
"Shattered" = "산산조각 난"
"Short" = "짧은"
"Shriveled" = "쪼글쪼글한"
"Sick" = "병든"
"Sienna" = "황갈색"
"Silent" = "침묵하는"
"Silken" = "비단 같은"
"Silky" = "매끄러운"
"Silty" = "토사가 섞인"
"Silvery" = "은빛"
"Simple" = "단순한"
"Sinful" = "죄 많은"
"Singed" = "그을린"
"Single" = "단일"
"Sunken" = "가라앉은"
"Sizzling" = "지글거리는"
"Skewered" = "꼬치에 꿰인"
"Skinny" = "깡마른"
"Slick" = "미끄러운"
"Slim" = "날씬한"
"Slippery" = "미끄러운"
"Slitted" = "갈라진"
"Sloppy" = "엉성한"
"Slow" = "느린"
"Sly" = "교활한"
"Small" = "작은"
"Smeared" = "얼룩진"
"Smooth" = "부드러운"
"Snarling" = "으르렁거리는"
"Soaked" = "흠뻑 젖은"
"Soapy" = "비누투성이"
"Socketed" = "끼워진"
"Solitary" = "고독한"
"Somber" = "어두침침한"
"Sooty" = "그을음 묻은"
"Sorcerous" = "마법"
"Sour" = "신"
"South" = "남쪽"
"Spattered" = "튀겨진"
"Special" = "특별한"
"Speckled" = "반점이 있는"
"Speechless" = "말문이 막힌"
"Spicy" = "매운"
"Spidery" = "거미줄 같은"
"Spiteful" = "악의적인"
"Splattered" = "튀겨진"
"Split" = "갈라진"
"Spongy" = "스펀지 같은"
"Spotted" = "얼룩진"
"Sprayed" = "뿌려진"
"Spread" = "퍼진"
"Spry" = "활기찬"
"Spurting" = "분출하는"
"Square" = "네모난"
"Squashed" = "짓눌린"
"Squat" = "땅딸막한"
"Squeezing" = "쥐어짜는"
"Stable" = "안정된"
"Stale" = "퀴퀴한"
"Static" = "정적인"
"Steamy" = "김이 나는"
"Stern" = "엄격한"
"Sticky" = "끈적이는"
"Still" = "정지한"
"Stinky" = "악취 나는"
"Stirred" = "휘저어진"
"Stoked" = "불이 지펴진"
"Stormy" = "폭풍우 치는"
"Strange" = "이상한"
"Strangled" = "목 졸린"
"Strapping" = "건장한"
"Strategic" = "전략적인"
"Strong" = "강한"
"Strifeful" = "분쟁"
"Stunted" = "성장이 멈춘"
"Stupid" = "어리석은"
"Submerged" = "침수된"
"Subordinate" = "종속된"
"Subtle" = "미묘한"
"Sugary" = "달콤한"
"Suicidal" = "파멸적인"
"Sullen" = "침울한"
"Sunny" = "화창한"
"Superior" = "우월한"
"Sweet" = "달콤한"
"Sweltering" = "무더운"
"Swift" = "빠른"
"Symmetric" = "대칭적인"
"Systemic" = "체계적인"
"Taciturn" = "과묵한"
"Tactical" = "전술적인"
"Tainted" = "더럽혀진"
"Tall" = "키 큰"
"Tame" = "길들여진"
"Tan" = "황갈색"
"Tangled" = "얽힌"
"Tapered" = "끝이 뾰족한"
"Tattooed" = "문신을 한"
"Taupe" = "회갈색"
"Taut" = "팽팽한"
"Teal" = "청록색"
"Tempted" = "유혹받는"
"Tenacious" = "집요한"
"Tender" = "부드러운"
"Tenebrous" = "음침한"
"Tepid" = "미지근한"
"Terrible" = "끔찍한"
"Thin" = "얇은"
"Thrifty" = "검소한"
"Tight" = "단단한"
"Tiled" = "타일이 깔린"
"Tin" = "주석빛"
"Tired" = "피곤한"
"Torrid" = "찌는 듯이 더운"
"Torturous" = "고문 같은"
"Touchy" = "과민한"
"Tragic" = "비극적인"
"Trampled" = "짓밟힌"
"Tressed" = "머리를 땋은"
"Triangular" = "삼각형"
"Trifling" = "사소한"
"Trim" = "단정한"
"Trite" = "진부한"
"Trussed" = "묶인"
"Trustworthy" = "신뢰할 수 있는"
"TRUE" = "진실된"
"Truthful" = "정직한"
"Tufted" = "다발진"
"Turquoise" = "청록색"
"Twinkling" = "반짝이는"
"Ugly" = "못생긴"
"Ultimate" = "궁극적인"
"Umber" = "암갈색"
"Umbral" = "그림자"
"Unbridled" = "억제되지 않은"
"Uncertain" = "불확실한"
"Uncommon" = "드문"
"Undignified" = "품위 없는"
"Ungodly" = "불경한"
"Unholy" = "신성하지 않은"
"Unkempt" = "단정치 못한"
"Unnameable" = "형언할 수 없는"
"Unremarkable" = "평범한"
"Unseen" = "보이지 않는"
"Unspeakable" = "말할 수 없는"
"Unswerving" = "확고한"
"Untamed" = "길들여지지 않은"
"Unthinkable" = "상상할 수 없는"
"Untoward" = "불운한"
"Untrustworthy" = "신뢰할 수 없는"
"Unwelcome" = "환영받지 못하는"
"Useless" = "쓸모없는"
"Vanished" = "사라진"
"Veiled" = "베일에 싸인"
"Velvety" = "벨벳 같은"
"Venerable" = "존경받는"
"Vermilion" = "주홍색"
"Vigorous" = "활기찬"
"Vile" = "사악한"
"Violent" = "폭력적인"
"Violet" = "보라색"
"Virginal" = "순결한"
"Virtuous" = "덕 있는"
"Vulgar" = "저속한"
"Walled" = "성벽으로 둘러싸인"
"Waning" = "쇠퇴"
"Warm" = "따뜻한"
"Washed" = "씻긴"
"Watchful" = "경계하는"
"Wavy" = "물결치는"
"Waxy" = "밀랍 같은"
"Wayward" = "고집 센"
"Weak" = "약한"
"Wealthy" = "부유한"
"Weathered" = "풍화된"
"West" = "서쪽"
"Wet" = "젖은"
"Whimsical" = "변덕스러운"
"Whirling" = "소용돌이치는"
"Whiskered" = "수염 난"
"White" = "흰"
"Wicked" = "사악한"
"Wild" = "야생"
"Willful" = "고집스러운"
"Wilted" = "시든"
"Windy" = "바람 부는"
"Wise" = "지혜로운"
"Wispy" = "가느다란"
"Withered" = "시든"
"Wondrous" = "경이로운"
"Wooden" = "나무로 된"
"Wordy" = "장황한"
"Worried" = "걱정하는"
"Worshipful" = "숭배하는"
"Worthless" = "가치 없는"
"Worthy" = "가치 있는"
"Wretched" = "비참한"
"Yawning" = "하품하는"
"Yellow" = "노란"
"Young" = "젊은"
"Youthful" = "젊은"